p 'Yahtzee'
p 'How to play: (instructions here)'
p 'roll the dice'
p 'pick which dice to keep'
p 'roll again?'
p 'these are your dice'
p 'what category do you want to apply this to?'
p 'ok. I have your score recorded.'
p "next player's turn"
p 'show their turn with all the things'
p 'your turn again'
p 'keep going until all categories have been filled'
p 'total up the score'
p 'one of you wins the game!'
p 'want to play again?'
